### ISSUE TITLE
In this section font size is little bit small

### ISSUE THREAD

**Issue by LuminiNanayakkara** [merinpriyasha/Resume#3]
![Capture1](https://user-images.githubusercontent.com/68697851/148886925-6e325ab7-cad9-4d9a-a421-8c4bd5ce674b.PNG)

**Comment by merinpriyasha** [comment]
@LuminiNanayakkara , I added 'fst-italic' bootstrap class for designed above mention paragraph  part. therefor it's contain a default size. But I increased header font size as you say.  Is it ok now?
