### ISSUE TITLE
The first letter of the name is behind to the side navigation bar

### ISSUE THREAD

**Issue by RavinduHasanka** [merinpriyasha/Resume#5]
![image](https://user-images.githubusercontent.com/68393512/148954738-6681a7fa-9a04-4452-ab94-bdf9b668e968.png)

**Comment by merinpriyasha** [comment]
![Capture4](https://user-images.githubusercontent.com/68733175/149277481-c5209c74-6fe0-4938-8829-e2139a6b05e7.PNG)

- The above is what the resume on my screen looks like.
  According to the issue you have submitted , the first letter of the name does not missing on the navigation bar. May be it happened when screen size is changed.
- However I reduce the name font size and tried to resolve the issue you presented. I think it's right now.
- Let me know if it is still not correct.
